# Perform configurations on just the primary Ping Proxy
- name: Ping Proxy Log Configurations
  hosts: PingProxyMachines[0]
  tags: [ temp ]
  tasks:
  gather_facts: True
  vars_files:
      - infra-vars.yml
  become: yes
  become_user: "{{ func_user }}"
  roles:
      - { role: temp }