#!/bin/bash
#
# description: OPENDJ init script
# processname: opendj
# chkconfig: 234 20 80
 
#Location of JAVA_HOME (bin files)
export JAVA_HOME={{ jdk_location }}
 
#Add Java binary files to PATH
export PATH=$JAVA_HOME/bin:$PATH

#OPENDJ_HOME is the default user
OPENDJ_HOME={{ opendj_home }}

#OPENDJ_USER is the default user
export OPENDJ_USER={{ func_user }}
 
#OPENDJ_USAGE is the message if this script is called without any options
OPENDJ_USAGE="Usage: $0 {\e[00;32mstart\e[00m|\e[00;31mstop\e[00m|\e[00;31mrestart\e[00m}"
 
#SHUTDOWN_WAIT is wait time in seconds for java proccess to stop
SHUTDOWN_WAIT=20
 
opendj_pid() {
        echo `ps -fe | grep $OPENDJ_HOME | grep -v grep | tr -s " "|cut -d" " -f2`
}
 
start() {
  pid=$(opendj_pid)
  if [ -n "$pid" ]
  then
    echo -e "\e[00;31mOPENDJ is already running (pid: $pid)\e[00m"
  else
    # Start OPENDJ
    echo -e "\e[00;32mStarting OPENDJ\e[00m"
    /bin/su $OPENDJ_USER -c $OPENDJ_HOME/bin/start-ds
  fi
  return 0
}
 
stop() {
  pid=$(opendj_pid)
  if [ -n "$pid" ]
  then
    echo -e "\e[00;31mStoping OPENDJ\e[00m"
    #/bin/su -p -s /bin/sh $OPENDJ_USER
        sh $OPENDJ_HOME/bin/stop-ds
 
    let kwait=$SHUTDOWN_WAIT
    count=0;
    until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -gt $kwait ]
    do
      echo -n -e "\n\e[00;31mwaiting for processes to exit\e[00m";
      sleep 1
      let count=$count+1;
    done
 
  else
    echo -e "\e[00;31mOPENDJ is not running\e[00m"
  fi
 
  return 0
}
 
case $1 in
	start)
	  start
	;;
	stop)  
	  stop
	;;
	restart)
	  stop
	  start
	;;
	*)
		echo -e $OPENDJ_USAGE
	;;
esac    
exit 0
