#!/bin/bash
#
# description: PPS init script
# processname: pps
# chkconfig: 234 20 80
 
#Location of JAVA_HOME (bin files)
export JAVA_HOME={{ jdk_location }}
 
#Add Java binary files to PATH
export PATH=$JAVA_HOME/bin:$PATH

#PPS_HOME is the default user
PPS_HOME={{ ping_proxy_home }}

#PPS_USER is the default user
export PPS_USER={{ func_user }}
 
#PPS_USAGE is the message if this script is called without any options
PPS_USAGE="Usage: $0 {\e[00;32mstart\e[00m|\e[00;31mstop\e[00m|\e[00;31mrestart\e[00m}"
 
#SHUTDOWN_WAIT is wait time in seconds for java proccess to stop
SHUTDOWN_WAIT=20
 
pps_pid() {
        echo `ps -fe | grep $PPS_HOME | grep -v grep | tr -s " "|cut -d" " -f2`
}
 
start() {
  pid=$(pps_pid)
  if [ -n "$pid" ]
  then
    echo -e "\e[00;31mPPS is already running (pid: $pid)\e[00m"
  else
    # Start PPS
    echo -e "\e[00;32mStarting PPS\e[00m"
    /bin/su $PPS_USER -c $PPS_HOME/bin/start-proxy
  fi
  return 0
}
 
stop() {
  pid=$(pps_pid)
  if [ -n "$pid" ]
  then
    echo -e "\e[00;31mStoping PPS\e[00m"
    #/bin/su -p -s /bin/sh $PPS_USER
        sh $PPS_HOME/bin/stop-proxy
 
    let kwait=$SHUTDOWN_WAIT
    count=0;
    until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -gt $kwait ]
    do
      echo -n -e "\n\e[00;31mwaiting for processes to exit\e[00m";
      sleep 1
      let count=$count+1;
    done
 
  else
    echo -e "\e[00;31mPPS is not running\e[00m"
  fi
 
  return 0
}
 
case $1 in
	start)
	  start
	;;
	stop)  
	  stop
	;;
	restart)
	  stop
	  start
	;;
	*)
		echo -e $PPS_USAGE
	;;
esac    
exit 0
